FROM oven/bun:latest AS web-builder

WORKDIR /build
COPY web/package.json .
COPY web/bun.lock .
RUN bun install
COPY ./web .
COPY ./VERSION .
RUN DISABLE_ESLINT_PLUGIN='true' VITE_REACT_APP_VERSION=$(cat VERSION) bun run build

FROM nginx:alpine

COPY deploy/nginx/new-api.conf /etc/nginx/conf.d/default.conf
COPY --from=web-builder /build/dist /usr/share/nginx/html

EXPOSE 80
